apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  labels:
    app: sample
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.component }}
    spec:
      containers:
        - name: sample
          image: teja4360/{{ .Values.component }}:{{ .Values.version }}
          ports:
            - containerPort: 80